name: Dev release from master

on:
  workflow_dispatch:

jobs:
  dev-release:
    name: Releasing master as dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - gooddata-api-client
          - gooddata-pandas
          - gooddata-fdw
          - gooddata-sdk
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Dev version
        run: |
          LATEST_DEV=$(./scripts/next_dev.sh)
      - name: Install pip & tbump
        run: python -m pip install --upgrade pip tbump
      - name: Bump to dev
        run: tbump  --only-patch --non-interactive $LATEST_DEV
      - name: Install dependencies
        run: pip install build
      - name: Build ${{ matrix.component }}
        run: |
          cd ${{ matrix.component }}
          python -m build
      - name: Push ${{ matrix.component}} to pypi
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: ${{ matrix.component }}/dist
          verbose: true
