name: Hugo Versioned Docs
on:
  workflow_dispatch:
jobs:
  hugo-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Generate Versioned Docs
        uses: gooddata/gooddata-python-sdk/.github/actions/hugo-build-versioned-action@INFRA-1578-test-branch
      - name: htmltest
        run: |
          rm htmltest.sh
          wget https://raw.githubusercontent.com/gooddata/gooddata-python-sdk/master/scripts/htmltest.sh
          chmod +x ./htmltest.sh
          ./htmltest.sh -c docs/.htmltest.yml docs/public
